kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-landing-page
  namespace: nginx-app
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Welcome to OpenShift</title>
        <style>
            /* Global Styles */
            body {
                font-family: 'Roboto', Arial, sans-serif;
                margin: 0;
                padding: 0;
                background: linear-gradient(to bottom right, #007BFF, #6C757D);
                color: #fff;
                text-align: center;
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
                height: 100vh;
                overflow: hidden;
            }
    
            /* Header Section */
            h1 {
                font-size: 3rem;
                margin: 0;
                padding: 10px;
                background: rgba(255, 255, 255, 0.2);
                border-radius: 10px;
                display: inline-block;
                color: #fff;
                text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.6);
            }
    
            /* Subtext */
            p {
                font-size: 1.5rem;
                margin: 20px 0;
                line-height: 1.6;
                max-width: 600px;
                text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.5);
            }
    
            /* Call-to-Action Button */
            a {
                text-decoration: none;
                color: #007BFF;
                background: #fff;
                padding: 15px 25px;
                border-radius: 25px;
                font-size: 1.2rem;
                font-weight: bold;
                box-shadow: 0 4px 6px rgba(0, 0, 0, 0.2);
                transition: all 0.3s ease;
            }
    
            a:hover {
                background: #007BFF;
                color: #fff;
                box-shadow: 0 6px 8px rgba(0, 0, 0, 0.3);
                transform: translateY(-2px);
            }
    
            /* Footer */
            footer {
                position: absolute;
                bottom: 10px;
                font-size: 0.9rem;
                color: rgba(255, 255, 255, 0.7);
            }
        </style>
    </head>
    <body>
        <h1>Welcome to OpenShift</h1>
        <p>Experience the power of container orchestration and seamless scalability with Red Hat OpenShift. Your applications, reimagined.</p>
        <a href="https://www.openshift.com" target="_blank">Learn More</a>
        <footer>&copy; 2024 OpenShift | All rights reserved.</footer>
    </body>
    </html>
